Fixes #32 Implements APIs documentation url
arxanchain/wallet-sdk-py pull request #33
Opened 2018-03-13 09:02 UTC by Honghaohan2013

2018-03-15 02:18 UTC, genggjh requested changes

2018-03-15 02:18 UTC, genggjh commented on README.md
> +Details of Wallet APIs please refer to [Wallet APIs Documentation](http://www.arxanfintech.com/infocenter/html/development/wallet.html#wallet-platform-ref)
you should provide SDK manual and procedure of create wallet account, create asset and etc, instead just provide APIs doc simply here.

2018-03-23 03:21 UTC, ivy-dong commented on README.md
> +...     "access": "username001",
password rules

2018-03-23 03:26 UTC, ivy-dong commented on README.md
> +* `Callback-Url` in http header is optional. If you want to receive blockchain transaction
`receive` or `subscribe` ?

2018-03-23 03:27 UTC, ivy-dong commented on README.md
> +>>> created = 123456 ## timestamp when poe is created
created string type timestamp

2018-03-23 03:28 UTC, ivy-dong commented on README.md
> +...     "metadata": {
metadata []byte type

2018-03-23 03:33 UTC, ivy-dong commented on README.md
> +>>> resp = wallet.register(header, body)
_, resp = wallet.register(header, body)

2018-03-23 04:04 UTC, ivy-dong commented on README.md
> +to 'sync' value. In synchronous mode, it will not return until the blockchain
add sync mode header example

2018-03-29 09:22 UTC, Honghaohan2013 commented on README.md
> +...     "access": "username001",
Added

2018-03-29 09:23 UTC, Honghaohan2013 commented on README.md
> +>>> created = 123456 ## timestamp when poe is created
Fixed

2018-03-29 09:42 UTC, Honghaohan2013 commented on README.md
> +>>> resp = wallet.register(header, body)
Fixed

2018-03-29 09:42 UTC, Honghaohan2013 commented on README.md
> +to 'sync' value. In synchronous mode, it will not return until the blockchain
Done

2018-04-09 08:35 UTC, tonyyang132 requested changes

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +Blockchain Wallet SDK includes APIs for the management of wallet accounts(DID),
for managing wallet accounts (Decentralized Identifiers, DID)

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +digital assets(POE), colored tokens etc.
digital assets (Proof of Existence, POE)

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +Welcome for any kind of contributions, such as open issues, fix bugs and improve documentation
We appreciate all kinds of contributions, such as opening issues, fixing bugs and improving documentation.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +The following command will install wallet-sdk-py in your python environment
in your python environment.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +**Note:** Before using the wallet-sdk-python in your operating system,
in your application

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +you need to configure your installed py-common package,
py-common package.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +for more details please refer to [usage of py-common](https://github.com/arxanchain/py-common#usage)
For more ...
[the usage of py-common](...)

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +Details of Wallet APIs please refer to
For details ...

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* At building the client configuration, the **url** and **apikey** fields must
When building

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +After creating wallet client, you can use this client to register wallet account
After creating the wallet client, you can use it to register a wallet account

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* `Callback-Url` in http header is optional. If you want to receive blockchain transaction
in the http header
Set it only if you want to receive events.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +After creation wallet account, you can create POE asset for this account as follows:
After creating the wallet account, you can create POE assets with this account as follows:

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* At creating POE asset, the **name** and **owner** fields must be set, and the
When creating a POE asset, ... be set, with **owner** being the wallet account ID.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* At building the signature parameter, using the ed25519 private key returned
When building
use the ...

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +After creation POE, you can upload POE file for this account as follows:
After creating
upload the POE file

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* `upload` API uploads the file to **Offchain** storage, and generates SHA256
The `upload` API ..., generates an SHA256 hash value, and saves ...

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +Once you have specified asset, you can use this specified asset to issue colored
Once you have possessed an asset, you can use this specific asset to issue colored tokens as follows:

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +* At issuing colored token, you need to specify an issuer(one wallet account ID),
When issuing colored tokens
an issuer (a wallet account ID)

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +an asset to be used to issue token, and the owner(another wallet account ID) who
an asset to issue tokens, and the owner (...).

(owner already means the one who has the asset)

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +After issuing colored token, the asset owner's wallet account will have these
colored tokens
will have these tokens

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +colored tokens, and can transfer some of them to other wallet account.
other wallet accounts.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +### Using callback URL to receive blockchain transaction event
Use
events

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +Each of the APIs for invoking blockchain has two invoking modes, one is `sync`
APIs to invoke ... two invoking modes - `sync` and `async`.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +'Callback-Url' in http header used to receive blockchain transaction event.
in the http header to receive blockchain transaction events.

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +One blockchain transaction event sample as follows:
A blockchain ...

2018-04-09 08:35 UTC, tonyyang132 commented on README.md
> +If you want to switch to synchronous invoking mode, set 'Bc-Invoke-Mode' header
set the ... header to `sync`.

2018-04-09 09:04 UTC, tonyyang132 requested changes

2018-04-09 09:04 UTC, tonyyang132 commented on README.md
> +* At building the signature parameter, using the ed25519 private key returned
When building the signature parameter `privateB64`, use the Base64 encoded ED25519 private key returned by [the registering API](#register-a-wallet-client).

2018-04-12 08:12 UTC, tonyyang132 approved these changes

2018-04-12 08:20 UTC, ivy-dong approved these changes

2018-04-12 08:26 UTC, merged