Adapt to Client
arxanchain/wallet-sdk-py pull request #37
Opened 2018-04-19 08:39 UTC by Honghaohan2013

2018-04-19 12:19 UTC, ewangplay requested changes

2018-04-19 12:19 UTC, ewangplay commented on api/poe.py
> +    def __init__(self, config):
config -> client

2018-04-19 12:19 UTC, ewangplay commented on api/poe.py
> +        """Init POE client with Config. """
common rest client

2018-04-20 04:09 UTC, ivy-dong approved these changes

2018-04-20 04:09 UTC, ewangplay approved these changes

2018-04-20 04:10 UTC, merged